### ISSUE TITLE
s-stm32.ads port from STM32F4 to STM32F0

### ISSUE THREAD

**Issue by bmilanov** [AdaCore/bb-runtimes#1]
Hi all,

The current src/s-stm32.ads is stm32f4-specific, which is incompatible with stm32f0. Examples of this are:
- Number of TIMCLKs and PCLKs
- Device IDs
- GPIO speed constants
- PLL sources due to clock tree differences

I have copy-pasted-modified the s-stm32.ads to s-stm32f0.ads for this reason.

Should I edit the python build scripts to rename s-stm32f0.ads to s-stm32.ads during RTS/BSP dirtree generation, or are these differences better addressed with one s-stm32.ads file and "if (ARCH = STM32F0)"-like conditions?

**Comment by lambourg** [comment]
Hello,

s-stm32 is deemed to be replaced at some point by i-stm32-* packages generated from svd.

In the mean time, the proper way to handle the cpu differences is to use the <base>__<variant>.ad[bs] naming schema, and add the proper handling in arm/cortexm.py. The python library automatically detects the __variant in source files and properly install it as <base>.ad[bs] in the runtime.

Best regards,
- Jerome

**Comment by bmilanov** [comment]
Okay, will stick with the naming schema. Thanks!
