### ISSUE TITLE
can't seem to find the working version

### ISSUE THREAD

**Issue by silentTee** [AdaCore/bb-runtimes#22]
Hello, I can't seem to identify the branch that is stable for use on Debian 10. The README instructions don't seem to quite sync up with the state of each branch, so I am a bit confused how to proceed.

I have tried building for x86 baremetal. Has support for this fallen to the wayside?

**Comment by Fabien-Chouteau** [comment]
Hello @silentTee, this repository doesn't provide a solution for baremetal x86.

One solution I have for you at the moment is to have a look at this tutorial (it might be outdated though): https://wiki.osdev.org/Ada_Bare_bones
