### ISSUE TITLE
Cannot find memory-map_nrf52840.ld

### ISSUE THREAD

**Issue by Feqzz** [AdaCore/bb-runtimes#35]
When trying to generate runtimes for nrf52840 it is trying to find the file `bb-runtimes/arm/nordic/nrf52/memory-map_nrf52840.ld`.
This file does not exist, although the file `memory-map_nRF52840.ld` exists. (nrf --> nRF).

Input:
`./build_rts.py --output=temp nrf52840`

~~At this moment I cannot confirm if simply changing the filename works, as I have other problems down the line.~~

It works!

**Comment by Fabien-Chouteau** [comment]
Hello @Feqzz ,

We actually have a patch for that but I forgot to merge it to the `community-2020` branch.
It is now fixed.

Thanks for the report,
