### ISSUE TITLE
Not sure if read/write on zynq7000's UART works

### ISSUE THREAD

**Issue by BottCode** [AdaCore/bb-runtimes#37]
Hi, I'm working with ravenscar-full on zynq7000 (GNAT CE 2018) and I'm struggling on reading data from UART with [cutecom](https://gitlab.com/cutecom/cutecom).

I've tried with multiple output functions: `System.Text_IO.Put`, `Ada.Text_IO.Put` and also `GNAT.IO.Put`, but nothing on cutecom's console appears.
I've also tried to switch from UART-1 to UART-0 just changing `Base : constant := 16#e000_1000#;` to `Base : constant := 16#e000_0000#;` in `System.Text_IO` package, but the outcome is the same.

The following is my cutecom configuration.
![image](https://user-images.githubusercontent.com/16674092/94195132-e8b48580-feb2-11ea-9a07-edc22556ea7c.png)

Thanks in advance for any advice.

**Comment by Fabien-Chouteau** [comment]
Hello @BottCode,

I am sorry we are not able to check this at the moment. You can maybe plug a logic analyzer to UART and see if there are some signals.
