### ISSUE TITLE
Cannot build with FSF GNAT

### ISSUE THREAD

**Issue by robdaemon** [AdaCore/bb-runtimes#60]
In light of the recent announcement of the EOL of GNAT Community, it would be great to be able to build these runtimes against FSF GNAT.

This would mean including `rts_sources.json` and other applicable files in the GCC tree (or even here, in this repo)

This repo has a Raspberry Pi 3, AArch64 RTS in it, but it hasn't been possible to build it as GNAT Community never provided an AArch64 build.

**Comment by Fabien-Chouteau** [comment]
Hello @robdaemon, the intent of this repository is mostly to support the addition of new board support package (BSP) for the targets supported by GNAT Community (arm-elf and RISC-V). Now that GNAT Community is discontinued, you can achieve the same with the GNAT FSF release provided by Alire.

At this point we do not plan to enable the support of targets that were not previously available in GNAT Community, like aarch64-elf.

**Comment by dinkelk** [comment]
`Now that GNAT Community is discontinued, you can achieve the same with the GNAT FSF release provided by Alire.`

Is there any documentation available on how to build these runtimes against the Alire GNAT FSF releases? Using the normal `./build_rts.py` method doesn't seem to work with the way the Alire packages are set up. It cannot find a `rts-sources.json` file. Is there a different method?

**Comment by Fabien-Chouteau** [comment]
Right now you have to use the corresponding `gnat-fsf-XX` branch from from this fork: https://github.com/Fabien-Chouteau/bb-runtimes
It contains `rts-sources.json` and the required sources.

For instance with GNAT FSF arm-elf 12:
```
./build_rts.py --rts-src-descriptor=gnat_rts_sources/lib/gnat/rts-sources.json --output=temp_build_rts --force --build stm32f4 tms570 lm3s rpi-pico rpi-pico-smp
```

**Comment by dinkelk** [comment]
@Fabien-Chouteau - Thank you, that works!
